eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10

spring:
  resources:
    static-locations:
      - classpath:/static/
      - classpath:/public/
      - file://${user.dir}/client/app/
      - file://${user.dir}/client/.tmp/
      - file://${user.dir}/client/

  jpa:
    show-sql: true
  # redis
  redis:
    host: localhost
    port: 6379

  # mongodb
  data:
    monogodb:
      uri: mongodb://localhost/sjes
      host: localhost
      port: 27017
